apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 294069345642.dkr.ecr.ap-south-1.amazonaws.com/devops-backend:4907017f5cc23a11b4be008be498d2fcee82f66b
          ports:
            - containerPort: 3000
