apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 294069345642.dkr.ecr.ap-south-1.amazonaws.com/devops-backend:4f79465c772e364415f60035717ca211053a9bef
          ports:
            - containerPort: 3000
